/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppAchievementsRouteImport } from './routes/_app/achievements'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppBattlePassRouteImport } from './routes/_app/battle-pass'
import { Route as AppChatRouteImport } from './routes/_app/chat'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppFriendsRouteImport } from './routes/_app/friends'
import { Route as AppHistoryRouteImport } from './routes/_app/history'
import { Route as AppInventoryRouteImport } from './routes/_app/inventory'
import { Route as AppMissionsRouteImport } from './routes/_app/missions'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppReferralsRouteImport } from './routes/_app/referrals'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppStatsRouteImport } from './routes/_app/stats'
import { Route as AppStoreRouteImport } from './routes/_app/store'
import { Route as AppWalletRouteImport } from './routes/_app/wallet'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as PublicCareersRouteImport } from './routes/_public/careers'
import { Route as PublicContactRouteImport } from './routes/_public/contact'
import { Route as PublicFaqRouteImport } from './routes/_public/faq'
import { Route as PublicLeaderboardRouteImport } from './routes/_public/leaderboard'
import { Route as PublicPrivacyRouteImport } from './routes/_public/privacy'
import { Route as PublicTermsRouteImport } from './routes/_public/terms'
import { Route as PublicWinnersRouteImport } from './routes/_public/winners'
import { Route as PlayGameIdRouteImport } from './routes/play.$gameId'
import { Route as AppPlayIndexRouteImport } from './routes/_app/play.index'
import { Route as PublicGiveawaysIndexRouteImport } from './routes/_public/giveaways.index'
import { Route as PublicGiveawaysIdRouteImport } from './routes/_public/giveaways.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAchievementsRoute = AppAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppBattlePassRoute = AppBattlePassRouteImport.update({
  id: '/battle-pass',
  path: '/battle-pass',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppFriendsRoute = AppFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppMissionsRoute = AppMissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppReferralsRoute = AppReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppStatsRoute = AppStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AppRoute,
} as any)
const AppStoreRoute = AppStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AppRoute,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCareersRoute = PublicCareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const PublicFaqRoute = PublicFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLeaderboardRoute = PublicLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPrivacyRoute = PublicPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTermsRoute = PublicTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => PublicRoute,
} as any)
const PublicWinnersRoute = PublicWinnersRouteImport.update({
  id: '/winners',
  path: '/winners',
  getParentRoute: () => PublicRoute,
} as any)
const PlayGameIdRoute = PlayGameIdRouteImport.update({
  id: '/play/$gameId',
  path: '/play/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPlayIndexRoute = AppPlayIndexRouteImport.update({
  id: '/play/',
  path: '/play/',
  getParentRoute: () => AppRoute,
} as any)
const PublicGiveawaysIndexRoute = PublicGiveawaysIndexRouteImport.update({
  id: '/giveaways/',
  path: '/giveaways/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicGiveawaysIdRoute = PublicGiveawaysIdRouteImport.update({
  id: '/giveaways/$id',
  path: '/giveaways/$id',
  getParentRoute: () => PublicRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/achievements': typeof AppAchievementsRoute
  '/admin': typeof AppAdminRoute
  '/battle-pass': typeof AppBattlePassRoute
  '/chat': typeof AppChatRoute
  '/dashboard': typeof AppDashboardRoute
  '/friends': typeof AppFriendsRoute
  '/history': typeof AppHistoryRoute
  '/inventory': typeof AppInventoryRoute
  '/missions': typeof AppMissionsRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/referrals': typeof AppReferralsRoute
  '/settings': typeof AppSettingsRoute
  '/stats': typeof AppStatsRoute
  '/store': typeof AppStoreRoute
  '/wallet': typeof AppWalletRoute
  '/about': typeof PublicAboutRoute
  '/careers': typeof PublicCareersRoute
  '/contact': typeof PublicContactRoute
  '/faq': typeof PublicFaqRoute
  '/leaderboard': typeof PublicLeaderboardRoute
  '/privacy': typeof PublicPrivacyRoute
  '/terms': typeof PublicTermsRoute
  '/winners': typeof PublicWinnersRoute
  '/play/$gameId': typeof PlayGameIdRoute
  '/giveaways/$id': typeof PublicGiveawaysIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/play/': typeof AppPlayIndexRoute
  '/giveaways/': typeof PublicGiveawaysIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/achievements': typeof AppAchievementsRoute
  '/admin': typeof AppAdminRoute
  '/battle-pass': typeof AppBattlePassRoute
  '/chat': typeof AppChatRoute
  '/dashboard': typeof AppDashboardRoute
  '/friends': typeof AppFriendsRoute
  '/history': typeof AppHistoryRoute
  '/inventory': typeof AppInventoryRoute
  '/missions': typeof AppMissionsRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/referrals': typeof AppReferralsRoute
  '/settings': typeof AppSettingsRoute
  '/stats': typeof AppStatsRoute
  '/store': typeof AppStoreRoute
  '/wallet': typeof AppWalletRoute
  '/about': typeof PublicAboutRoute
  '/careers': typeof PublicCareersRoute
  '/contact': typeof PublicContactRoute
  '/faq': typeof PublicFaqRoute
  '/leaderboard': typeof PublicLeaderboardRoute
  '/privacy': typeof PublicPrivacyRoute
  '/terms': typeof PublicTermsRoute
  '/winners': typeof PublicWinnersRoute
  '/play/$gameId': typeof PlayGameIdRoute
  '/giveaways/$id': typeof PublicGiveawaysIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/play': typeof AppPlayIndexRoute
  '/giveaways': typeof PublicGiveawaysIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/_app/achievements': typeof AppAchievementsRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/battle-pass': typeof AppBattlePassRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/friends': typeof AppFriendsRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/missions': typeof AppMissionsRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/referrals': typeof AppReferralsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/stats': typeof AppStatsRoute
  '/_app/store': typeof AppStoreRoute
  '/_app/wallet': typeof AppWalletRoute
  '/_public/about': typeof PublicAboutRoute
  '/_public/careers': typeof PublicCareersRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/faq': typeof PublicFaqRoute
  '/_public/leaderboard': typeof PublicLeaderboardRoute
  '/_public/privacy': typeof PublicPrivacyRoute
  '/_public/terms': typeof PublicTermsRoute
  '/_public/winners': typeof PublicWinnersRoute
  '/play/$gameId': typeof PlayGameIdRoute
  '/_public/': typeof PublicIndexRoute
  '/_public/giveaways/$id': typeof PublicGiveawaysIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/play/': typeof AppPlayIndexRoute
  '/_public/giveaways/': typeof PublicGiveawaysIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/achievements'
    | '/admin'
    | '/battle-pass'
    | '/chat'
    | '/dashboard'
    | '/friends'
    | '/history'
    | '/inventory'
    | '/missions'
    | '/notifications'
    | '/profile'
    | '/referrals'
    | '/settings'
    | '/stats'
    | '/store'
    | '/wallet'
    | '/about'
    | '/careers'
    | '/contact'
    | '/faq'
    | '/leaderboard'
    | '/privacy'
    | '/terms'
    | '/winners'
    | '/play/$gameId'
    | '/giveaways/$id'
    | '/api/auth/$'
    | '/play/'
    | '/giveaways/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/achievements'
    | '/admin'
    | '/battle-pass'
    | '/chat'
    | '/dashboard'
    | '/friends'
    | '/history'
    | '/inventory'
    | '/missions'
    | '/notifications'
    | '/profile'
    | '/referrals'
    | '/settings'
    | '/stats'
    | '/store'
    | '/wallet'
    | '/about'
    | '/careers'
    | '/contact'
    | '/faq'
    | '/leaderboard'
    | '/privacy'
    | '/terms'
    | '/winners'
    | '/play/$gameId'
    | '/giveaways/$id'
    | '/api/auth/$'
    | '/play'
    | '/giveaways'
  id:
    | '__root__'
    | '/_app'
    | '/_public'
    | '/login'
    | '/onboarding'
    | '/_app/achievements'
    | '/_app/admin'
    | '/_app/battle-pass'
    | '/_app/chat'
    | '/_app/dashboard'
    | '/_app/friends'
    | '/_app/history'
    | '/_app/inventory'
    | '/_app/missions'
    | '/_app/notifications'
    | '/_app/profile'
    | '/_app/referrals'
    | '/_app/settings'
    | '/_app/stats'
    | '/_app/store'
    | '/_app/wallet'
    | '/_public/about'
    | '/_public/careers'
    | '/_public/contact'
    | '/_public/faq'
    | '/_public/leaderboard'
    | '/_public/privacy'
    | '/_public/terms'
    | '/_public/winners'
    | '/play/$gameId'
    | '/_public/'
    | '/_public/giveaways/$id'
    | '/api/auth/$'
    | '/_app/play/'
    | '/_public/giveaways/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PlayGameIdRoute: typeof PlayGameIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/achievements': {
      id: '/_app/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AppAchievementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/battle-pass': {
      id: '/_app/battle-pass'
      path: '/battle-pass'
      fullPath: '/battle-pass'
      preLoaderRoute: typeof AppBattlePassRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/friends': {
      id: '/_app/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof AppFriendsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/missions': {
      id: '/_app/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof AppMissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/referrals': {
      id: '/_app/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof AppReferralsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stats': {
      id: '/_app/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AppStatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/store': {
      id: '/_app/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof AppStoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wallet': {
      id: '/_app/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/careers': {
      id: '/_public/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof PublicCareersRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/faq': {
      id: '/_public/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof PublicFaqRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/leaderboard': {
      id: '/_public/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof PublicLeaderboardRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/privacy': {
      id: '/_public/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PublicPrivacyRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/terms': {
      id: '/_public/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof PublicTermsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/winners': {
      id: '/_public/winners'
      path: '/winners'
      fullPath: '/winners'
      preLoaderRoute: typeof PublicWinnersRouteImport
      parentRoute: typeof PublicRoute
    }
    '/play/$gameId': {
      id: '/play/$gameId'
      path: '/play/$gameId'
      fullPath: '/play/$gameId'
      preLoaderRoute: typeof PlayGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/play/': {
      id: '/_app/play/'
      path: '/play'
      fullPath: '/play/'
      preLoaderRoute: typeof AppPlayIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_public/giveaways/': {
      id: '/_public/giveaways/'
      path: '/giveaways'
      fullPath: '/giveaways/'
      preLoaderRoute: typeof PublicGiveawaysIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/giveaways/$id': {
      id: '/_public/giveaways/$id'
      path: '/giveaways/$id'
      fullPath: '/giveaways/$id'
      preLoaderRoute: typeof PublicGiveawaysIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAchievementsRoute: typeof AppAchievementsRoute
  AppAdminRoute: typeof AppAdminRoute
  AppBattlePassRoute: typeof AppBattlePassRoute
  AppChatRoute: typeof AppChatRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFriendsRoute: typeof AppFriendsRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppMissionsRoute: typeof AppMissionsRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReferralsRoute: typeof AppReferralsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStatsRoute: typeof AppStatsRoute
  AppStoreRoute: typeof AppStoreRoute
  AppWalletRoute: typeof AppWalletRoute
  AppPlayIndexRoute: typeof AppPlayIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAchievementsRoute: AppAchievementsRoute,
  AppAdminRoute: AppAdminRoute,
  AppBattlePassRoute: AppBattlePassRoute,
  AppChatRoute: AppChatRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFriendsRoute: AppFriendsRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppMissionsRoute: AppMissionsRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppReferralsRoute: AppReferralsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStatsRoute: AppStatsRoute,
  AppStoreRoute: AppStoreRoute,
  AppWalletRoute: AppWalletRoute,
  AppPlayIndexRoute: AppPlayIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicCareersRoute: typeof PublicCareersRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicFaqRoute: typeof PublicFaqRoute
  PublicLeaderboardRoute: typeof PublicLeaderboardRoute
  PublicPrivacyRoute: typeof PublicPrivacyRoute
  PublicTermsRoute: typeof PublicTermsRoute
  PublicWinnersRoute: typeof PublicWinnersRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicGiveawaysIdRoute: typeof PublicGiveawaysIdRoute
  PublicGiveawaysIndexRoute: typeof PublicGiveawaysIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicCareersRoute: PublicCareersRoute,
  PublicContactRoute: PublicContactRoute,
  PublicFaqRoute: PublicFaqRoute,
  PublicLeaderboardRoute: PublicLeaderboardRoute,
  PublicPrivacyRoute: PublicPrivacyRoute,
  PublicTermsRoute: PublicTermsRoute,
  PublicWinnersRoute: PublicWinnersRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicGiveawaysIdRoute: PublicGiveawaysIdRoute,
  PublicGiveawaysIndexRoute: PublicGiveawaysIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PlayGameIdRoute: PlayGameIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
